### ISSUE TITLE
Where is yarn being installed to?

### ISSUE THREAD

**Issue by partridge420x** [citizenfx/cfx-server-data#129]
Under resources/system/builders/yarn i see the script for the server plugin, But im not seeing where you guys packaged the binaries for yarn. 

Im getting a EROFS: Read Only Filesystem, Yarn install failed. and i need to know where the binaries are being downloaded to fix the issue

**Comment by partridge420x** [comment]
![image](https://user-images.githubusercontent.com/26298829/98169744-d3bc1080-1eba-11eb-929b-d7eebc535c6f.png)

**Comment by gameplayoffert** [comment]
i have this problem too

**Comment by technetium-cfx** [comment]
Please use our [forums](https://forum.cfx.re/) or [Discord](https://discord.gg/fivem) for these kind of questions.
