### ISSUE TITLE
Couldn't start resource chat.

### ISSUE THREAD

**Issue by worapolburaphan** [citizenfx/cfx-server-data#130]
![image](https://user-images.githubusercontent.com/12433101/98432917-3d276380-20f5-11eb-879a-154196313a9d.png)

I don't know to solve this issue

Artifact version: 2769
cfx-server-data : 'v2.1'

**Comment by gameplayoffert** [comment]
i have this problem too

**Comment by technetium-cfx** [comment]
Please use our [forums](https://forum.cfx.re/) or [Discord](https://discord.gg/fivem) for these kind of questions.

**Comment by phelippe** [comment]
I solved this problem uninstaling my yarn from global packages `npm uninstall -g yarn`
