### ISSUE TITLE
Couldn't start resource chat.

### ISSUE THREAD

**Issue by gameplayoffert** [citizenfx/cfx-server-data#132]
hi, i post this again because i have open a topic for that : https://forum.cfx.re/t/couldnt-start-ressource-chat-yarn-failed/1774231 and i have post this to the five m discord and i don't get any answer so you are the only one who can answer to me so why i have this error :

![np2c4sL](https://user-images.githubusercontent.com/20711503/98693369-7c151d80-2370-11eb-9e5f-ebaa2a6503d5.png)

![kssUw0A](https://user-images.githubusercontent.com/20711503/98693423-8fc08400-2370-11eb-8d48-e1909ede435d.png)

**Comment by technetium-cfx** [comment]
And I will tell you again that this is not the place to post such issues. Please stick with the forums.

**Comment by phelippe** [comment]
I solved this problem uninstaling my yarn from global packages `npm uninstall -g yarn`
