### ISSUE TITLE
not work good

### ISSUE THREAD

**Issue by johnsoul777** [citizenfx/cfx-server-data#141]
chat:addTemplate

![image](https://user-images.githubusercontent.com/72218928/102973376-e63ae980-44fc-11eb-9ea0-f78cf0a1b12c.png)

**Comment by blattersturm** [comment]
not write good

**Comment by johnsoul777** [comment]
> no escribir bien

TriggerEvent('chat:addTemplate', 'barrio', "<img src='data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyNC4zLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgdmlld0JveD0iMCAwIDkwMi41OSA3NTQuNyIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgOTAyLjU5IDc1NC43OyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPg0KCS5zdDB7c3Ryb2tlOiNGRkZGRkY7c3Ryb2tlLXdpZHRoOjI7c3Ryb2tlLW1pdGVybGltaXQ6MTA7fQ0KCS5zdDF7ZmlsbDojOTE5MTkxO3N0cm9rZTojRkZGRkZGO3N0cm9rZS13aWR0aDoyO3N0cm9rZS1taXRlcmxpbWl0OjEwO30NCgkuc3Qye2ZpbGw6dXJsKCNPam9fMV8xXyk7c3Ryb2tlOiMwMDAwMDA7c3Ryb2tlLXdpZHRoOjI7c3Ryb2tlLW1pdGVybGltaXQ6MTA7fQ0KCS5zdDN7ZmlsbDp1cmwoI09qb18yXzFfKTtzdHJva2U6IzAwMDAwMDtzdHJva2Utd2lkdGg6MjtzdHJva2UtbWl0ZXJsaW1pdDoxMDt9DQo8L3N0eWxlPg0KPGcgaWQ9IlRyYXpvcyI+DQoJPGc+DQoJCTxwYXRoIGlkPSJNYXRyaXpfTG9nbyIgY2xhc3M9InN0MCIgZD0iTTI3Mi40OSwxODEuNTRDNDQ0LjAxLDUuOTQsNjIxLjU4LTEyLjMsODU2LjAxLDcuMjNMNzUxLjE0LDE3My44DQoJCQljMjM2LjQ4LDUzLjQ3LDE2NS41NCwyMTYuODQtMTUuNzIsMTk5LjQxQzcxMy44Miw1MDEuNzMsNjEyLjMzLDc1My43LDUwMC4yNiw3NTMuN2MtMjUuNy0xMDYuOTMtNDcuMTEtMTc3Ljg4LTE0OS44Ny0yMzQuOTcNCgkJCWMtMTkuNTQsNDAuMS0zOS4zMSw5NC4xMS0yNDguMDQsMTQ0LjQ5YzYuMTctNjIuNzIsMjUuMTgtMTE0LjI4LDUxLjY1LTE1OS42MUM5Mi4zMSw0ODUuMSwxLjU5LDQ2My43NSwxLjU5LDQ2My43NQ0KCQkJczQ2LjI3LTc0LjAyLDE0Ni0xMTguMjRjLTEuMDMtNTguNjEsMzguMDQtMTMxLjYxLDE0Mi4xMy0xNDMuOTVMMjcyLjQ5LDE4MS41NHoiLz4NCgkJPHBhdGggaWQ9IkZvbmRvX0xvZ29fMV8iIGNsYXNzPSJzdDEiIGQ9Ik0zMjEuMjIsMTc5LjUxQzQ2Ny41Miw1Mi44LDYwMS43MywyMy4yMiw3OTMuMDksMzMuOTljMCwwLTYzLjg2LDc4LjQ0LTEwNC44NCwxNjIuNDcNCgkJCWMxODguNSwxMS44NCwyNjMuMDcsMTU3Ljg0LDIwLjE4LDE0Mi4xMkM2OTAuOTMsNDQyLjY5LDYwMy41OCw2ODQuOCw1MjAuMjYsNzE1LjQ5Yy0yMy40MS0xMzcuMDUtOTkuOTgtMjA2LjkxLTE5MS4xMi0yNDYuODcNCgkJCWMtMTUuODMsMzIuNDgtMTMuNzEsMTA1LjI1LTE4Mi43OSwxNDYuMDZjMTAuMTctNTguODcsMjkuMTctOTUuMjIsNjEuNzktMTQxLjk5Yy03Ny44NC04LjQ4LTk4LjE5LTE2LjYxLTE1Mi40OS0zMC40Nw0KCQkJYzMwLjY1LTI3LjI2LDU0LjYtNTMuOTgsMTI2LjctNzIuNjljLTI4LjE5LTEwMS42LDcwLjAzLTE0NS41NywxNzcuMDItMTQ1LjA4TDMyMS4yMiwxNzkuNTF6Ii8+DQoJCTxwYXRoIGlkPSJTb21icmVyb18xIiBkPSJNMzMzLjIzLDE3OS4yNEM0MjYuMjEsOTYuMyw1NTkuODgsMjIuOTUsNzgwLjUxLDQwLjQ1QzczNi44LDkzLjAyLDY3Mi4yOSwxNzkuOTIsNjU3LjksMjU5LjQ0DQoJCQljLTEzNC4zNS0yMy45OS0xMjAuOTgtNDguNjctMzA1LjcxLTY2LjQ5YzY5LjkyLTguOTEsMTA2LjY2LTEzLjAyLDE4My43LTIuMDZjLTM0LjM1LTExLjI5LTQ1LTEzLjk1LTk3Ljc4LTE3LjM4DQoJCQljMzkuNzctMTEuMSwxNjMuNTgtMTQuMTUsMjE0LjMxLTEuODFjMTcuNTUtMzcuODQsNDEuMTMtNzYuNzcsNTkuNjMtOTguMDZjLTEwMC43NiwxMS43LTEzMS42MSwyMS45OC0yMzguMDUsNjcuNjYNCgkJCWM0NC4wNC0zMi40MSw1My4wMi0zNy4xNywxMDQuMzktNjEuNDVDNDczLjUxLDEwMS43OCw0MjIuMSwxMTguMjMsMzMzLjIzLDE3OS4yNHoiLz4NCgkJPHBhdGggaWQ9IlNvbWJyZXJvXzIiIGQ9Ik0yNzIuNjcsMzk5LjI3Yy0xNTcuNTIsMi45Ni0xMjYuNDctMjYwLjQ3LDI4MS4wNC0xMzQuMTFjMjAyLjksNjIuNDIsMTg3LjgyLDcuOTgsMTI2LjgxLTI0LjIzDQoJCQljMjYuNzMtMi43NCwxMDguOTksMzIuMjIsNzIuNDIsNTguMDJjOTMuMjItMTYuNDUsMTMuMzUtODAuNTYtNjQuMS05Ny4wMWM4MC44LDIuMzQsMTc1LjUxLDQ5LjkxLDE2My4yMSw5MC42OA0KCQkJYy0xMi44NCw0Mi41Ni0xMTYuNTQsNDYuNDYtMTc5Ljg5LDMxLjI1Yy0yMzYuMjYtNTYuNzYtMzAxLjgtOTguNzEtNDMzLjk5LTQwLjkzYy03LjkxLDMuNDYsMzcuOTQtMTIuNTQsNzUuNjQtOS4xMQ0KCQkJQzI4MC4yMSwyODguMjIsMTczLjI4LDMzOC4yNiwyNzIuNjcsMzk5LjI3eiIvPg0KCQk8cGF0aCBpZD0iT3JlamEiIGQ9Ik0zMjIuMDIsMzQxLjM1Yy00LjM3LTIzLjM5LDQuNTMtMzQuMzQsMTEuMzEtMzUuOTljMzguMDQtOS4yNSw2MC41LDU2LjMzLDQ0Ljc4LDgxLjU0DQoJCQljLTcuNzcsMTIuNDctMzMuNDcsMTIuNDctMzkuNzctMTEuMzZjLTMuNzItMTQuMDgsMi45NS0zOS4zMywyMy41Mi0yMy45MWMxLjI5LTEwLjAyLTE0LjY5LTM1LjEtMjguNjMtMzMuMTYNCgkJCUMzMTguOTQsMzIwLjQ2LDMyMi40NCwzNDAuNTEsMzIyLjAyLDM0MS4zNXoiLz4NCgkJPHJhZGlhbEdyYWRpZW50IGlkPSJPam9fMV8xXyIgY3g9IjQ4MC4xNDE1IiBjeT0iMzA1LjQ4MjUiIHI9IjUyLjIzNzMiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4NCgkJCTxzdG9wICBvZmZzZXQ9IjAiIHN0eWxlPSJzdG9wLWNvbG9yOiMzM0RERkYiLz4NCgkJCTxzdG9wICBvZmZzZXQ9IjAuNDk0NCIgc3R5bGU9InN0b3AtY29sb3I6IzQ1NzRGRiIvPg0KCQkJPHN0b3AgIG9mZnNldD0iMSIgc3R5bGU9InN0b3AtY29sb3I6IzdDMDBGRiIvPg0KCQk8L3JhZGlhbEdyYWRpZW50Pg0KCQk8cGF0aCBpZD0iT2pvXzEiIGNsYXNzPSJzdDIiIGQ9Ik00OTIuMDIsMzI3LjNjLTE5LjU0LTE0LjkyLTQ0LjA1LTI4LjQ2LTgyLjQ1LTQzLjYzYzU0Ljg0LDMuNDMsOTAuMzMsMTEuMjMsMTQxLjE2LDI2LjQ5DQoJCQlDNTIzLjM1LDMxNS4wNiw1MDkuNzgsMzE4Ljg4LDQ5Mi4wMiwzMjcuM3oiLz4NCgkJPHJhZGlhbEdyYWRpZW50IGlkPSJPam9fMl8xXyIgY3g9IjY1OC44NzQ3IiBjeT0iMzQzLjM2NjUiIHI9IjI3LjQxMzkiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4NCgkJCTxzdG9wICBvZmZzZXQ9IjAiIHN0eWxlPSJzdG9wLWNvbG9yOiMzM0RERkYiLz4NCgkJCTxzdG9wICBvZmZzZXQ9IjAuNDk0NCIgc3R5bGU9InN0b3AtY29sb3I6IzQ1NzRGRiIvPg0KCQkJPHN0b3AgIG9mZnNldD0iMSIgc3R5bGU9InN0b3AtY29sb3I6IzdDMDBGRiIvPg0KCQk8L3JhZGlhbEdyYWRpZW50Pg0KCQk8cGF0aCBpZD0iT2pvXzIiIGNsYXNzPSJzdDMiIGQ9Ik02MjIuNzQsMzI5LjMyYzI2LjIxLDUuNDcsNDUuNywxMC43Myw3Mi4yNywxNS43N2MtMTcuNzUsOC4wOC0yOC42LDE0LjM3LTQyLjQzLDExLjcNCgkJCUM2MzkuMjIsMzU0LjIsNjI4Ljc0LDM0Mi41Miw2MjIuNzQsMzI5LjMyeiIvPg0KCQk8cGF0aCBpZD0iTWFzY2FyYSIgZD0iTTYwOS4yMywzMzQuMTVjMTYuNDUsNTQuMDgsNDIuODgsNDkuMTIsNTYuNDUsNTguNzFjLTMuNjcsNTUuMDgtMjAuNCw4NC43Mi01MC4yOCwxNDEuNDUNCgkJCWMzLjA0LTI3LjIsNS42NS00Ni4xLDEzLjIyLTc1LjMxYy00Mi4zNiw5Mi43OS01NC44OSwxMjQuMjctNzkuNzEsMTc0LjcxYy0yOS43Ny04Mi42LTc4LjgzLTExNC4zNi0xMzkuMTUtMTUzLjU0DQoJCQljMjcuMzItMi4wNiw1NC4xNS02Ljg1LDk2LjM2LTMyLjEzYy03My41NSwxNy44Ny05Ni41NiwyMS4xNi0xNzcuOTMsOS41MWMxMjMuNCw2Ny44NiwxNjkuNjUsMTE4LjI0LDE5OS43NSwyNDYuOTkNCgkJCWM1NS4yNC0zMC4zOSwxNTguNzQtMjMxLjIzLDE1OC43NC0zMjkuOTNDNjQ1LjU2LDM3My43Miw2MzQuNTksMzY1LDYwOS4yMywzMzQuMTV6Ii8+DQoJCTxwYXRoIGlkPSJOYXJpeiIgZD0iTTUyMy41NSw0MDMuMDRjLTcxLjk2LDQzLjE4LTE3OC45LDM3LjAxLTIxMC43OCwxNy45NmMxMDYuOTMtMjUuODQsMTg5LjE5LTg4LjA1LDI2OC4xMS04OS45NA0KCQkJYzYuNy05LjEyLDIuODctMy43NywxMi41OC0yMi42MmMyLjA2LDM4LjA0LDEwLjI4LDU2LjU1LDQ0LjIxLDExMy4xYy0xNC4yNCwxNy4zOC00MC4xLDMwLjg1LTQwLjEsMzAuODVsLTMxLjkzLTI4LjNsMzcuNjgtMTIuODENCgkJCWMwLDAtMTkuMTItMzMuMDItMjMuMjMtNTQuNTFjLTQwLjg4LTMuNzgtMTEwLjUzLDQyLjU5LTE2Ny42NSw1NC41NUM0NTEuNTksNDE1LjEyLDQ3NS4yMiw0MTEuMzQsNTIzLjU1LDQwMy4wNHoiLz4NCgkJPHBhdGggaWQ9Ikxhem9fMSIgZD0iTTIxMy4xNSw0MTEuMjZjLTEzLjQ4LDQuODItMzEuOTksMC01MS43NywxNy40OGMzOC44LDIuMDYsNTcuMDEsMS4yNCw4NC43NS04LjMzDQoJCQljLTU3LjM1LTYwLjMyLTEwOC43NS00NC44LTE3NC4yNiwxNy42NGM2Ny42NywxOS43MiwxMzEuNiwzNC4xMiwxNjAuNywzLjU0Yy03MC45NCwxMC44LTk3LjY5LTIuMDEtMTI3LjUtMTAuOA0KCQkJQzE0NC42NiwzOTguMjUsMTc0LjQ4LDM4Ny4xLDIxMy4xNSw0MTEuMjZ6Ii8+DQoJCTxwYXRoIGQ9Ik0xNTcuMzEsNjAyLjgxYzE3NS45Mi0zMy43MiwxNjguMzEtMTU0LjAxLDE1OS4yMy0xNjIuNzVjLTM1LjEzLDE1Ljk0LTQxLjMsMjMuMTMtODAuMiw2MS40NQ0KCQkJYzI5LjY1LDAuNzYsMzguMTQtMTMuNDgsNjMuNi0yOC44NWMtMTYuOTcsNDUuNzUtNzAuMDMsOTguODUtMTE2LjgxLDEwMi40NWMxNC4zOS03My41Miw3NC45LTEyMC45LDEwMS4yOS0xNDIuNDkNCgkJCUMyMDguMTYsNDMyLjIsMTU3LjA4LDU2OS44MSwxNTcuMzEsNjAyLjgxeiIvPg0KCTwvZz4NCjwvZz4NCjxnIGlkPSJDYXBhXzIiPg0KPC9nPg0KPC9zdmc+DQo=' height='16'> <b>{0}</b>: {1}")

**Comment by blattersturm** [comment]
i doubt i wrote in spanish

weird stuff
