### ISSUE TITLE
Chat Not Disappearing 

### ISSUE THREAD

**Issue by concapalot** [citizenfx/cfx-server-data#152]
The chat box used to disappear after typing or not going into the chat box, but now it just stays there and it can get really annoying and become an eye-sore.

**Comment by blattersturm** [comment]
Okay? Is this even actionable? Have you tried pressing the chat toggle key?

**Comment by concapalot** [comment]
Yes the chat works perfectly fine, but after typing in it, the chat box wont disappear like it used to.

**Comment by blattersturm** [comment]
Works fine here too. Again, how is this actionable?

**Comment by concapalot** [comment]
Because the box is supposed to disappear as well as the messages inside.

**Comment by blattersturm** [comment]
It does though? And if it doesn't, literally press the L key or whatever you've bound it to a few times.

Again, what part here is actionable?

**Comment by concapalot** [comment]
Oh I see with the L keybind. Im used to it automatically closing on its own without having to set it to When Active etc.
