### ISSUE TITLE
Man-In-The middle attack due to SSL CERT

### ISSUE THREAD

**Issue by emxia** [citizenfx/cfx-server-data#155]
The default certificate generated by the FXServer is trusted implicitly by the FiveM Client.
Users should always be warned - or have the option to accept the risk of connecting to servers which present an TLS Certificate not signed by a trust root certificate authority such as let's encrypt.

It seems the certificate is generated by FXServer in the event that none is present. 
Users should be generating their own SSL Certificates if it's for friends, and using a service like let's encrypt, or COMODO, etc, if it's monetized, since it will be easy to provide justification. 

![image](https://user-images.githubusercontent.com/79781376/109578069-b132b080-7ac4-11eb-9c5e-4150020aef60.png)

![image](https://user-images.githubusercontent.com/79781376/109578034-a2e49480-7ac4-11eb-81f8-2518b80375e8.png)

![image](https://user-images.githubusercontent.com/79781376/109578012-97916900-7ac4-11eb-8c79-59db2528da4d.png)

**Comment by blattersturm** [comment]
Nah. TLS is not used to provide secrecy here, only because client libraries don't implement h2 over non-TLS.

**Comment by emxia** [comment]
Malicious client scripts could be uploaded via mitm...
