### ISSUE TITLE
Chat is lagging

### ISSUE THREAD

**Issue by NylanderrDK** [citizenfx/cfx-server-data#160]
The chat-module is lagging for some of my players.
They tap T, the chat opens, but the input only shows up after about 10 seconds.
I can't reproduce the issue. There isn't anything useful (I guess) that I can provide - but if there is, please hit me up.

**Comment by blattersturm** [comment]
Not the right place for this.

**Comment by NylanderrDK** [comment]
Oh, I didn't know that.
Where should I post it then?
