### ISSUE TITLE
Both my friend and I have tried to setup a server but both can't connect with a 1604 error

### ISSUE THREAD

**Issue by Mshriver2** [citizenfx/cfx-server-data#165]
Error received: "server specified an invalid game enforcement (1604)"

**Comment by Mshriver2** [comment]
@blattersturm Why did you close this? I still have not gotten a response here, the forums, and reddit. Could you at least give some advice before closing??

**Comment by AvarianKnight** [comment]
This isn't the place for support, use the forums.

**Comment by Mshriver2** [comment]
@AvarianKnight I have tried posting to the forum for the last week+ none of my posts are ever showing up on the forums / approved by mods.
