### ISSUE TITLE
Current master HEAD is not working

### ISSUE THREAD

**Issue by nurumaik** [citizenfx/cfx-server-data#170]
0210252be7c17745fa30220e12c19e0d2f19af02 with (recommended) 3593 server version doesn't work on linux (redm stucks on infinite loading screen with no errors in console and no errors in server log)
7680f316a7a128ca09d27101dac572098c111242 with same server version works

My config 
```
endpoint_add_tcp "***:30120"
endpoint_add_udp "***:30120"

ensure esplugin_mysql
ensure mysql-async
ensure redem
ensure redem_roleplay
ensure redemrp_identity

sets tags "roleplay"

sets locale "ru-RU"

set es_enableCustomData 1
set mysql_connection_string "server=127.0.0.1;uid=root;password=iloveasians;database=redemrp"
sv_hostname "***"

add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.fivem:1 group.admin # add the admin to the group
add_ace resource.redem command.sets allow
add_ace resource.redem command.add_principal allow
add_ace resource.redem command.add_ace allow

sv_endpointprivacy true
sv_maxclients 32

set steam_webApiKey "***"

sv_licenseKey ***

ensure redemrp_respawn #example
```

Default config from https://forum.cfx.re/t/how-to-setup-a-redm-server/918850 also didn't work with current master with same error

It should have started somewhere around march, first report I have found is this https://forum.cfx.re/t/redm-infinite-loading-screen-when-joining-a-server/1851267/33?u=qman228

**Comment by Disquse** [comment]
This is not an issue. The latest server-data changes only work with experimental RedM canary changes. Later or sooner those changes will be pushed to production.
