### ISSUE TITLE
spawnmanger 

### ISSUE THREAD

**Issue by NoxieX** [citizenfx/cfx-server-data#186]
as soon as you edit the spawn manger its causes your server to be hanged on awaiting scripts this is a error that needs to be fixed asap

**Comment by technetium-cfx** [comment]
You shouldn't have to modify spawnmanager. In fact, the resources here are designed to be used as-is. If you need any functional changes, they are best provided through a pull request. If you need any scripting related help, please use our [forums](https://forum.cfx.re) or [Discord](https://discord.gg/fivem).
