### ISSUE TITLE
[ citizen-server-impl] [91mSome resources have an outdated resource manifest:

### ISSUE THREAD

**Issue by lrichards2011** [citizenfx/cfx-server-data#222]
[ citizen-server-impl] [91mSome resources have an outdated resource manifest:
[ citizen-server-impl]     - chat
[ citizen-server-impl]     - lux_vehcontrol
[ citizen-server-impl]     - postalmap
[ citizen-server-impl]     - ragdoll
[ citizen-server-impl] 
[ citizen-server-impl] Please update these resources.

Can someone please help me on updating this?

**Comment by AvarianKnight** [comment]
This isn't the police to request help use the [forums[(https://forums.cfx.re) instead
