### ISSUE TITLE
bug: TypeError: Cannot read property 'minify' of undefined Terser

### ISSUE THREAD

**Issue by d0p3t** [citizenfx/cfx-server-data#45]
**Expected Behavior:** webpack will build upon first start
**Current Behavior:** An error occurs regarding the minify's dependency `Terser`

`TypeError: Cannot read property 'minify' of undefined Terser`

**Reason:** Terser 3.16, which is required by minify (and thus webpack) currently breaks interoperability. 
See https://github.com/terser-js/terser/issues/251 
A fix is currently waiting to merged https://github.com/terser-js/terser/pull/254

**Solution:** In the meantime, any latest `webpack` version is broken, hence if anyone has issues building with webpack. If you'd like to use webpack, you can force the webpack builder to use 4.12.0 om the builders `package.json`

https://github.com/citizenfx/cfx-server-data/blob/master/resources/%5Bsystem%5D/%5Bbuilders%5D/webpack/package.json

`"webpack": "4.12.0",` instead of `"webpack": "^4.12.0",`

I wanted to report this issue for any users getting this error. I think no PR/fix is needed as this should be a temporary issue. Perhaps for any future issues webpack can stay at `4.12.0`?

**Comment by vecchiotom** [comment]
interesting indeed, i installed webpack yesterday and didnt have any problems, but a guy tried doing the same thing a couple hours later and had the error.

**Comment by d0p3t** [comment]
Bug has been fixed.
