### ISSUE TITLE
Yarn and webpack won't work on linux

### ISSUE THREAD

**Issue by LySoon** [citizenfx/cfx-server-data#81]
is there Any planned future updates for this ?

**Comment by Chukin95** [comment]
for windows dont work too

**Comment by bndzor** [comment]
If you run it through patchelf it does.

Also, it does work fine for windows.

**Comment by Chukin95** [comment]
J'ai essayé de lancer le fil et le Webpack pour le gcphone screenshot-basic et ils me demandent de neo-async, quand je le dis, il est dit que le néo-async est vieux, je pense

**Comment by blattersturm** [comment]
what is this nonsense
