### ISSUE TITLE
problems with basic-gamemode

### ISSUE THREAD

**Issue by manups4e** [citizenfx/cfx-server-data#86]
if a different resource changes gametype in manifest.. basic-gamemode stops it at startup.. and cannot be disabled since if i start the resource that changes gametype basic-gamemode gets stopped and resource "fivem" depends on basic-gamemode.. 

1. server starts 
2. resource fivem starts and basic-gamemode starts changing gametype to "Freeroam"
3. my gamemode gets stopped on startup because basic-gamemode loads with it
4. if i start manually my gamemode basic-gamemode gets stopped
5. if i enter the server FiveM client won't load resources as resource fivem misses its dependency basic-gamemode

**Comment by blattersturm** [comment]
Huh? Define `changes gametype in manifest` 😮 Are you starting two gametypes?

Is the issue rather that dependencies do not propagate a stop?

**Comment by manups4e** [comment]
actually yeah.. my gamemode changes gametype to a custom one

**Comment by blattersturm** [comment]
Moved to client issues: https://forum.fivem.net/t/dependencies-do-not-propagate-on-stop/925042

As a workaround, you could also simply not `start fivem`.

**Comment by manups4e** [comment]
it's not required to start?

**Comment by blattersturm** [comment]
> 
> 
> it's not required to start?

it's just the old name for `basic-gamemode`, if you have your own gametype you'll just use that

**Comment by manups4e** [comment]
the fact that when i start my gamemode, basic-gamemode gets stopped automatically is normal?

**Comment by manups4e** [comment]
also.. you wrote "if fivem gets started manually" that's incorrect for me.. as i manually start my gamemode (and that's where basic-gamemode gets stopped by the server automatically)
only when i try to load inside i get fivem resource error on dependency

**Comment by jonathancwhite** [comment]
did you figure out the error @manups4e I am having the same issue. I am going through the tutorial for fivem scripting and it's giving me the "Could not find dependency basic-gamemode for resource fivem." error and then gives a global error "Couldn't start resource fivem. :("

**Comment by manups4e** [comment]
yeah... you could just read 5 posts above... https://github.com/citizenfx/cfx-server-data/issues/86#issuecomment-567559412

**Comment by IntrovertedBeginner** [comment]
I know extended mode can cause this error. Check to see if your scripts resource manifest files are setting gametypes, e.g. https://prnt.sc/upvv0h, if they are then, goto your server.cfg and (#) comment out the "start fivem" and you should be set.

**Comment by MubarakLala12** [comment]
basic-gamemodes  download like
