### ISSUE TITLE
unable to get Network ids for entities or request for control of ent. 

### ISSUE THREAD

**Issue by TheStonedRaider** [citizenfx/cfx-server-data#90]
From a perfect connection the "NetworkGetNetworkIdFromEntity" and "NetworkRequestControlOfEntity" work fine. but after some time, mostly after an obvious freeze (that happen often to everyone i know). the server will not return anything from these two functions, and it seems any others that ask anything of the network. "NetworkGetNetworkIdFromEntity" simply returns false and "NetworkRequestControlOfEntity" also returns false and will not give you control of any entity.

**Comment by cerium-cfx** [comment]
Not an issue with cfx-server-data. If you believe you have found a bug, whether GTA 5 or FiveM related, report it at https://forum.cfx.re/c/general-discussion/bug-reports/28
