### ISSUE TITLE
Weird Vehicle issue on linux server

### ISSUE THREAD

**Issue by Madzahttr** [citizenfx/cfx-server-data#93]
sorry if this is the wrong place for this, I've already created a forum post which ended up dead

Having a weird issue where some add on vehicles won't spawn, they're loaded by the server but won't spawn, (using vmenu and simpletrainer for spawning) the menus detect that they exist, but when trying to spawn them, it stutters for a second, then says its spawned, but it hasn't and nothing even gets logged to the ingame console, the working vehicles will either spawn straight away or log that they are being downloaded.

Everything works fine on the windows server, and i tested another linux server using WSL and the same problem occured. 

Windows server is running artifact 2007 on windows 1909
Linux server is running artifact 2001 (have tried others, issue was not fixed) on ubuntu 18.04.1

**Comment by deadmp-deneb** [comment]
You ever think that this is an issue with the resource you’re using to spawn said vehicles, rather than FiveM itself?

**Comment by Madzahttr** [comment]
deffinately not, both simpletrainer (client side) and vMenu spawn them fine on the windows server, and both fail to spawn the vehicles on the linux server

**Comment by Shrimpey** [comment]
*"No script guid for vehicle..."* this does not seem right.
Firstly, make a raw server with just one of the vehicles you're having problems with and a resource to spawn it. Disable ALL the other resources and check what's happening then.

**Comment by Madzahttr** [comment]
already tried all of that, and the no script guide for vehicle error was completely unrelated and has since been fixed

**Comment by Shrimpey** [comment]
Yet, the fact that you had it fixed means that either you had something messed up with vehicle resource (so there's high probability that you still do) or you were still running some non-standard resources causing it. Make it as raw as you can to eliminate any kind of irrelevant sources of possible errors, only then we can check if it's really related to the OS you're using for the server.

**Comment by Madzahttr** [comment]
already tried all the obvious things, isolating, trying on a different server, trying different artifacts.

that handling error only on a few poorly done vehicles that were trying to load a handling file that they didn't have and had gone un-noticed till now, all the vehicles have worked fine until trying to use them on a linux server. the only thing i can think of is that the linux artifacts are somehow different in how it loads vehicles, because it all runs fine on windows

**Comment by Shrimpey** [comment]
I *highly* doubt that it's the case of server OS as you spawn vehicles clientside (via vMenu's clientsided part), also I know quite a few car based servers running on Linux that do not have any problems like that. That is why it is probably case of your vehicle spawner or resources itself, so I'm telling you to isolate those things as you had quite a few vehicle resources in the video that you posted. 
Server could be failing to stream vehicles to the client, but again, that probably is the problem with how you set up vehicle resources.

**Comment by Madzahttr** [comment]
again, they *all* work perfectly fine on the windows server

I have isolated the vehicles, and ran them one at a time, and attempted to spawn them with 3 different menus, simpletrainer, lambda and vMenu, all have the same result of stuttering for a seccond, logging absolutely nothing and then acting as if the vehicle has been spawned

**Comment by nathanctech** [comment]
This is sadly the wrong place for this problem as it has nothing to do with any code in the repository. If you come to the community discord and provide reproduction steps (maybe provide one or more vehicles experiencing the issue, or is it any?) it can be investigated further.

**Comment by Madzahttr** [comment]
I've been on the forum and the discord, all to no avail, which is why I ended up here, if you'd like a copy of a couple of the cars, send me a friend request, Madzahttr#0001 on discord

**Comment by hojgr** [comment]
honestly this is perfect place to resolve such issue... since its an issue with linux build its very much to do with the code. Nobody on discord can help in any other way, other then contributing a patch to this very codebase.

**Comment by Madzahttr** [comment]
Exactly, if it's working on one, but not the other, theirs clearly something wrong with the server itself

**Comment by nathanctech** [comment]
> honestly this is perfect place to resolve such issue... since its an issue with linux build its very much to do with the code. Nobody on discord can help in any other way, other then contributing a patch to this very codebase.

I think you confuse this with the actual FiveM repository where the code actually lives. Issues are closed there because the forums are the appropriate place to report issues. This repository is for the default resources that every server will have and this issue is **not** because of that.

**Comment by Madzahttr** [comment]
The forum was useless for this, post died after a few replies, things in discord just get buried, and as you said, issues are closed on the main repo. I think I'll stick to here until the issue is resolved, or a cfx person says to go elsewhere

**Comment by Seb5a** [comment]
Send me your vehicle files on my discord seb5a#0013 and I’ll look at them. They are corrupted probably and in my opinion it’s not problem with fivem server but with files.

**Comment by Madzahttr** [comment]
Really don't see how they'd be corrupted, they work perfectly fine on the windows server.
I'll add you once I'm home in a few hours

**Comment by TehRamsus** [comment]
Yeah. we have exactly same "problem"

**Comment by Madzahttr** [comment]
Forgot about this issue, ended up being a case issue with the stream folder having a capital S.
