### ISSUE TITLE
Patreon subscription

### ISSUE THREAD

**Issue by root-dm** [citizenfx/cfx-server-data#96]
Hello i bought a patreon subscription today and i am trying to run server with one sync tells me that i am not whitelisted

**Comment by Something-Debug** [comment]
So you though the GitHub repo was the proper place to ask for help?

**Comment by root-dm** [comment]
No one answers both patreon & emails

**Comment by smallo92** [comment]
Try the discord server. This is not the place for support.

**Comment by cerium-cfx** [comment]
Not an issue with cfx-server-data
