### ISSUE TITLE
Can I run CFX without this resource?

### ISSUE THREAD

**Issue by riflowth** [citizenfx/cfx-server-data#97]
Belong to a topic...
What should I do?

**Comment by blattersturm** [comment]
What?

**Comment by riflowth** [comment]
Can I rewrite cfx-server-data to Javascript or something alternatively

**Comment by blattersturm** [comment]
Why would you?

**Comment by blattersturm** [comment]
Also, this kind of questions should go on the [forums](https://forum.cfx.re), not here.
